from typing import NamedTuple, Type, Any


class AttributeSelector(NamedTuple):
    xpath: str
    type: Type[Any]


VEHICLE_ATTRIBUTE_SELECTORS = {
    # "title": AttributeSelector(xpath="//div//h1[contains(@class, 'main-title-listing')]/text()", type=str),
    # "price": AttributeSelector(xpath="//div//span[contains(@class, 'price-heading')]/text()", type=str),
    # "article_id": AttributeSelector(xpath="//div//label[svg/path[@d='M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z']]/text()", type=str),
    # "sold": AttributeSelector(xpath="//div[@class='finished-listing']", type=bool),
    "location": AttributeSelector(xpath="//div[svg//path[@d='M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z']]/text()", type=str),
    "state": AttributeSelector(xpath="//div[svg/path[@d='M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z']]/text()", type=str),
    "brand": AttributeSelector(xpath="//div//h4[normalize-space(text())='Proizvođač']/following-sibling::h4[1]//text()", type=str),
    "model": AttributeSelector(xpath="//div//h4[normalize-space(text())='Model']/following-sibling::h4[1]//text()", type=str),
    "fuel_type": AttributeSelector(xpath="//div//h4[normalize-space(text())='Gorivo']/following-sibling::h4[1]//text()", type=str),
    "build_year": AttributeSelector(xpath="//div//h4[normalize-space(text())='Godište']/following-sibling::h4[1]//text()", type=str),
    "mileage": AttributeSelector(xpath="//div//h4[normalize-space(text())='Kilometraža']/following-sibling::h4[1]//text()", type=str),
    "engine_volume": AttributeSelector(xpath="//div//h4[normalize-space(text())='Kubikaža']/following-sibling::h4[1]//text()", type=str),
    "engine_power": AttributeSelector(xpath="//div//h4[normalize-space(text())='Snaga motora (KW)']/following-sibling::h4[1]//text()", type=str),
    "num_doors": AttributeSelector(xpath="//div//h4[normalize-space(text())='Broj vrata']/following-sibling::h4[1]//text()", type=str),
    "transmission": AttributeSelector(xpath="//div//h4[normalize-space(text())='Transmisija']/following-sibling::h4[1]//text()", type=str),
    "image_url": AttributeSelector(xpath="//div[@class='main-image-overlay-content']//div[@class='gallery-items']/img[1]/@src", type=str),
    "horsepower": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Konjskih snaga']/following-sibling::h4[1]//text()", type=str),
    "weight_kg": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Masa/Težina (kg)']/following-sibling::h4[1]//text()", type=str),
    "vehicle_type": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Tip']/following-sibling::h4[1]//text()", type=str),
    "climate": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Klimatizacija']/following-sibling::h4[1]//text()", type=str),
    "audio": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Muzika/ozvučenje']/following-sibling::h4[1]//text()", type=str),
    "parking_sensors": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Parking senzori']/following-sibling::h4[1]//text()", type=str),
    "parking_camera": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Parking kamera']/following-sibling::h4[1]//text()", type=str),
    "drivetrain": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Pogon']/following-sibling::h4[1]//text()", type=str),
    "year_first_registered": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Godina prve registracije']/following-sibling::h4[1]//text()", type=str),
    "registered_until": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Registrovan do']/following-sibling::h4[1]//text()", type=str),
    "color": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Boja']/following-sibling::h4[1]//text()", type=str),
    "gears": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Broj stepeni prijenosa']/following-sibling::h4[1]//text()", type=str),
    "tyres": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Posjeduje gume']/following-sibling::h4[1]//text()", type=str),
    "emission": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Emisioni standard']/following-sibling::h4[1]//text()", type=str),
    "interior": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Vrsta enterijera']/following-sibling::h4[1]//text()", type=str),
    "curtains": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Rolo zavjese']/following-sibling::h4[1]//text()", type=str),
    "lights": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Svjetla']/following-sibling::h4[1]//text()", type=str),
    "number_of_seats": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Sjedećih mjesta']/following-sibling::h4[1]//text()", type=str),
    "rim_size": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Veličina felgi']/following-sibling::h4[1]//text()", type=str),
    "warranty": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Garancija']/following-sibling::h4[1]//text()", type=str),
    "security": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Zaštita/Blokada']/following-sibling::h4[1]//text()", type=str),
    "previous_owners": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Broj prethodnih vlasnika']/following-sibling::h4[1]//text()", type=str),
    "published_at": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Datum objave']/following-sibling::h4[1]//text()", type=str),
    "registered": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Registrovan']", type=bool),
    "metallic": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Metalik']", type=bool),
    "alloy_wheels": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Alu felge']", type=bool),
    "digital_air_conditioning": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Digitalna klima']", type=bool),
    "steering_wheel_controls": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Komande na volanu']", type=bool),
    "navigation": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Navigacija']", type=bool),
    "touch_screen": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Touch screen (ekran)']", type=bool),
    "heads_up_display": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Head up display']", type=bool),
    "usb_port": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='USB port']", type=bool),
    "cruise_control": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Tempomat']", type=bool),
    "bluetooth": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Bluetooth']", type=bool),
    "car_play": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Car play']", type=bool),
    "rain_sensor": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Senzor kiše']", type=bool),
    "park_assist": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Park assist']", type=bool),
    "automatic_light_sensor": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Senzor auto. svjetla']", type=bool),
    "blind_spot_sensor": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Senzor mrtvog ugla']", type=bool),
    "start_stop_system": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Start-Stop sistem']", type=bool),
    "hill_assist": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Hill assist']", type=bool),
    "seat_memory": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Memorija sjedišta']", type=bool),
    "seat_massage": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Masaža sjedišta']", type=bool),
    "seat_heating": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Grijanje sjedišta']", type=bool),
    "seat_cooling": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Hlađenje sjedišta']", type=bool),
    "electric_windows": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='El. podizači stakala']", type=bool),
    "electric_seat_adjustment": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='El. pomjeranje sjedišta']", type=bool),
    "armrest": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Naslon za ruku']", type=bool),
    "panoramic_roof": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Panorama krov']", type=bool),
    "sunroof": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Šiber']", type=bool),
    "fog_lights": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Maglenke']", type=bool),
    "electric_mirrors": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Električni retrovizori']", type=bool),
    "alarm": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Alarm']", type=bool),
    "central_lock": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Centralna brava']", type=bool),
    "remote_unlock": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Daljinsko otključavanje']", type=bool),
    "airbag": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Airbag']", type=bool),
    "abs": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='ABS']", type=bool),
    "electronic_stability": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='ESP']", type=bool),
    "dpf_fap_filter": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='DPF/FAP filter']", type=bool),
    "power_steering": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Servo volan']", type=bool),
    "turbo": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Turbo']", type=bool),
    "isofix": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='ISOFIX']", type=bool),
    "tow_hook": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Auto kuka']", type=bool),
    "customs_cleared": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Ocarinjen']", type=bool),
    "foreign_license_plates": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Strane tablice']", type=bool),
    "on_lease": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Na lizingu']", type=bool),
    "service_history": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Servisna knjiga']", type=bool),
    "damaged": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Udaren']", type=bool),
    "disabled_accessible": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Prilagođen invalidima']", type=bool),
    "oldtimer": AttributeSelector(xpath="//div[@class='tbody']//h4[normalize-space(text())='Oldtimer']", type=bool),
}
