from typing import NamedTuple, Type, Any


class XPathConfig(NamedTuple):
    path: str
    type: Type[Any]


ATTRIBUTE_XPATHS = {
    "title": XPathConfig(path="//div//h1[contains(@class, 'main-title-listing')]/text()", type=str),
    "price": XPathConfig(path="//div//span[contains(@class, 'price-heading')]/text()", type=str),
    "location": XPathConfig(path="//div//label[svg/path[@d='M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z']]/text()", type=str),
    "state": XPathConfig(path="//div//label[svg/path[@d='M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z']]/text()", type=str),
    "article_id": XPathConfig(path="//div//label[svg/path[@d='M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z']]/text()", type=str),
    "brand": XPathConfig(path="//div//td[normalize-space(text())='Proizvođač']/following-sibling::td[1]//text()", type=str),
    "model": XPathConfig(path="//div//td[normalize-space(text())='Model']/following-sibling::td[1]//text()", type=str),
    "fuel_type": XPathConfig(path="//div//td[normalize-space(text())='Gorivo']/following-sibling::td[1]//text()", type=str),
    "build_year": XPathConfig(path="//div//td[normalize-space(text())='Godište']/following-sibling::td[1]//text()", type=str),
    "mileage": XPathConfig(path="//div//td[normalize-space(text())='Kilometraža']/following-sibling::td[1]//text()", type=str),
    "engine_volume": XPathConfig(path="//div//td[normalize-space(text())='Kubikaža']/following-sibling::td[1]//text()", type=str),
    "engine_power": XPathConfig(path="//div//td[normalize-space(text())='Snaga motora (KW)']/following-sibling::td[1]//text()", type=str),
    "num_doors": XPathConfig(path="//div//td[normalize-space(text())='Broj vrata']/following-sibling::td[1]//text()", type=str),
    "transmission": XPathConfig(path="//div//td[normalize-space(text())='Transmisija']/following-sibling::td[1]//text()", type=str),
    "image_url": XPathConfig(path="//div[@class='main-image-overlay-content']//div[@class='gallery-items']/img[1]/@src", type=str),
    "horsepower": XPathConfig(path="//div//table//td[normalize-space(text())='Konjskih snaga']/following-sibling::td[1]//text()", type=str),
    "weight_kg": XPathConfig(path="//div//table//td[normalize-space(text())='Masa/Težina (kg)']/following-sibling::td[1]//text()", type=str),
    "vehicle_type": XPathConfig(path="//div//table//td[normalize-space(text())='Tip']/following-sibling::td[1]//text()", type=str),
    "climate": XPathConfig(path="//div//table//td[normalize-space(text())='Klimatizacija']/following-sibling::td[1]//text()", type=str),
    "audio": XPathConfig(path="//div//table//td[normalize-space(text())='Muzika/ozvučenje']/following-sibling::td[1]//text()", type=str),
    "parking_sensors": XPathConfig(path="//div//table//td[normalize-space(text())='Parking senzori']/following-sibling::td[1]//text()", type=str),
    "parking_camera": XPathConfig(path="//div//table//td[normalize-space(text())='Parking kamera']/following-sibling::td[1]//text()", type=str),
    "drivetrain": XPathConfig(path="//div//table//td[normalize-space(text())='Pogon']/following-sibling::td[1]//text()", type=str),
    "year_first_registered": XPathConfig(path="//div//table//td[normalize-space(text())='Godina prve registracije']/following-sibling::td[1]//text()", type=str),
    "registered_until": XPathConfig(path="//div//table//td[normalize-space(text())='Registrovan do']/following-sibling::td[1]//text()", type=str),
    "color": XPathConfig(path="//div//table//td[normalize-space(text())='Boja']/following-sibling::td[1]//text()", type=str),
    "gears": XPathConfig(path="//div//table//td[normalize-space(text())='Broj stepeni prijenosa']/following-sibling::td[1]//text()", type=str),
    "tyres": XPathConfig(path="//div//table//td[normalize-space(text())='Posjeduje gume']/following-sibling::td[1]//text()", type=str),
    "emission": XPathConfig(path="//div//table//td[normalize-space(text())='Emisioni standard']/following-sibling::td[1]//text()", type=str),
    "interior": XPathConfig(path="//div//table//td[normalize-space(text())='Vrsta enterijera']/following-sibling::td[1]//text()", type=str),
    "curtains": XPathConfig(path="//div//table//td[normalize-space(text())='Rolo zavjese']/following-sibling::td[1]//text()", type=str),
    "lights": XPathConfig(path="//div//table//td[normalize-space(text())='Svjetla']/following-sibling::td[1]//text()", type=str),
    "number_of_seats": XPathConfig(path="//div//table//td[normalize-space(text())='Sjedećih mjesta']/following-sibling::td[1]//text()", type=str),
    "rim_size": XPathConfig(path="//div//table//td[normalize-space(text())='Veličina felgi']/following-sibling::td[1]//text()", type=str),
    "warranty": XPathConfig(path="//div//table//td[normalize-space(text())='Garancija']/following-sibling::td[1]//text()", type=str),
    "security": XPathConfig(path="//div//table//td[normalize-space(text())='Zaštita/Blokada']/following-sibling::td[1]//text()", type=str),
    "previous_owners": XPathConfig(path="//div//table//td[normalize-space(text())='Broj prethodnih vlasnika']/following-sibling::td[1]//text()", type=str),
    "published_at": XPathConfig(path="//div//table//td[normalize-space(text())='Datum objave']/following-sibling::td[1]//text()", type=str),
    "registered": XPathConfig(path="//div//table//td[normalize-space(text())='Registrovan']/following-sibling::td[1]", type=bool),
    "metallic": XPathConfig(path="//div//table//td[normalize-space(text())='Metalik']/following-sibling::td[1]", type=bool),
    "alloy_wheels": XPathConfig(path="//div//table//td[normalize-space(text())='Alu felge']/following-sibling::td[1]", type=bool),
    "digital_air_conditioning": XPathConfig(path="//div//table//td[normalize-space(text())='Digitalna klima']/following-sibling::td[1]", type=bool),
    "steering_wheel_controls": XPathConfig(path="//div//table//td[normalize-space(text())='Komande na volanu']/following-sibling::td[1]", type=bool),
    "navigation": XPathConfig(path="//div//table//td[normalize-space(text())='Navigacija']/following-sibling::td[1]", type=bool),
    "touch_screen": XPathConfig(path="//div//table//td[normalize-space(text())='Touch screen (ekran)']/following-sibling::td[1]", type=bool),
    "heads_up_display": XPathConfig(path="//div//table//td[normalize-space(text())='Head up display']/following-sibling::td[1]", type=bool),
    "usb_port": XPathConfig(path="//div//table//td[normalize-space(text())='USB port']/following-sibling::td[1]", type=bool),
    "cruise_control": XPathConfig(path="//div//table//td[normalize-space(text())='Tempomat']/following-sibling::td[1]", type=bool),
    "bluetooth": XPathConfig(path="//div//table//td[normalize-space(text())='Bluetooth']/following-sibling::td[1]", type=bool),
    "car_play": XPathConfig(path="//div//table//td[normalize-space(text())='Car play']/following-sibling::td[1]", type=bool),
    "rain_sensor": XPathConfig(path="//div//table//td[normalize-space(text())='Senzor kiše']/following-sibling::td[1]", type=bool),
    "park_assist": XPathConfig(path="//div//table//td[normalize-space(text())='Park assist']/following-sibling::td[1]", type=bool),
    "automatic_light_sensor": XPathConfig(path="//div//table//td[normalize-space(text())='Senzor auto. svjetla']/following-sibling::td[1]", type=bool),
    "blind_spot_sensor": XPathConfig(path="//div//table//td[normalize-space(text())='Senzor mrtvog ugla']/following-sibling::td[1]", type=bool),
    "start_stop_system": XPathConfig(path="//div//table//td[normalize-space(text())='Start-Stop sistem']/following-sibling::td[1]", type=bool),
    "hill_assist": XPathConfig(path="//div//table//td[normalize-space(text())='Hill assist']/following-sibling::td[1]", type=bool),
    "seat_memory": XPathConfig(path="//div//table//td[normalize-space(text())='Memorija sjedišta']/following-sibling::td[1]", type=bool),
    "seat_massage": XPathConfig(path="//div//table//td[normalize-space(text())='Masaža sjedišta']/following-sibling::td[1]", type=bool),
    "seat_heating": XPathConfig(path="//div//table//td[normalize-space(text())='Grijanje sjedišta']/following-sibling::td[1]", type=bool),
    "seat_cooling": XPathConfig(path="//div//table//td[normalize-space(text())='Hlađenje sjedišta']/following-sibling::td[1]", type=bool),
    "electric_windows": XPathConfig(path="//div//table//td[normalize-space(text())='El. podizači stakala']/following-sibling::td[1]", type=bool),
    "electric_seat_adjustment": XPathConfig(path="//div//table//td[normalize-space(text())='El. pomjeranje sjedišta']/following-sibling::td[1]", type=bool),
    "armrest": XPathConfig(path="//div//table//td[normalize-space(text())='Naslon za ruku']/following-sibling::td[1]", type=bool),
    "panoramic_roof": XPathConfig(path="//div//table//td[normalize-space(text())='Panorama krov']/following-sibling::td[1]", type=bool),
    "sunroof": XPathConfig(path="//div//table//td[normalize-space(text())='Šiber']/following-sibling::td[1]", type=bool),
    "fog_lights": XPathConfig(path="//div//table//td[normalize-space(text())='Maglenke']/following-sibling::td[1]", type=bool),
    "electric_mirrors": XPathConfig(path="//div//table//td[normalize-space(text())='Električni retrovizori']/following-sibling::td[1]", type=bool),
    "alarm": XPathConfig(path="//div//table//td[normalize-space(text())='Alarm']/following-sibling::td[1]", type=bool),
    "central_lock": XPathConfig(path="//div//table//td[normalize-space(text())='Centralna brava']/following-sibling::td[1]", type=bool),
    "remote_unlock": XPathConfig(path="//div//table//td[normalize-space(text())='Daljinsko otključavanje']/following-sibling::td[1]", type=bool),
    "airbag": XPathConfig(path="//div//table//td[normalize-space(text())='Airbag']/following-sibling::td[1]", type=bool),
    "abs": XPathConfig(path="//div//table//td[normalize-space(text())='ABS']/following-sibling::td[1]", type=bool),
    "electronic_stability": XPathConfig(path="//div//table//td[normalize-space(text())='ESP']/following-sibling::td[1]", type=bool),
    "dpf_fap_filter": XPathConfig(path="//div//table//td[normalize-space(text())='DPF/FAP filter']/following-sibling::td[1]", type=bool),
    "power_steering": XPathConfig(path="//div//table//td[normalize-space(text())='Servo volan']/following-sibling::td[1]", type=bool),
    "turbo": XPathConfig(path="//div//table//td[normalize-space(text())='Turbo']/following-sibling::td[1]", type=bool),
    "isofix": XPathConfig(path="//div//table//td[normalize-space(text())='ISOFIX']/following-sibling::td[1]", type=bool),
    "tow_hook": XPathConfig(path="//div//table//td[normalize-space(text())='Auto kuka']/following-sibling::td[1]", type=bool),
    "customs_cleared": XPathConfig(path="//div//table//td[normalize-space(text())='Ocarinjen']/following-sibling::td[1]", type=bool),
    "foreign_license_plates": XPathConfig(path="//div//table//td[normalize-space(text())='Strane tablice']/following-sibling::td[1]", type=bool),
    "on_lease": XPathConfig(path="//div//table//td[normalize-space(text())='Na lizingu']/following-sibling::td[1]", type=bool),
    "service_history": XPathConfig(path="//div//table//td[normalize-space(text())='Servisna knjiga']/following-sibling::td[1]", type=bool),
    "damaged": XPathConfig(path="//div//table//td[normalize-space(text())='Udaren']/following-sibling::td[1]", type=bool),
    "disabled_accessible": XPathConfig(path="//div//table//td[normalize-space(text())='Prilagođen invalidima']/following-sibling::td[1]", type=bool),
    "oldtimer": XPathConfig(path="//div//table//td[normalize-space(text())='Oldtimer']/following-sibling::td[1]", type=bool),
}
